app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import Required


class BlogForm(FlaskForm):
    title = StringField('Title', validators=[Required()])
    content = TextAreaField('quote', validators=[Required()])

    submit = SubmitField('Submit')


class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.', validators=[Required()])
    submit = SubmitField('Submit')


class CommentForm(FlaskForm):
    content = TextAreaField('Add comment', validators=[Required()])
    submit = SubmitField()
    
class UpForm(FlaskForm):
    title = StringField('Title', validators=[Required()])
    content = TextAreaField('quote', validators=[Required()])

    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy
from config import Config_options

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
bootstrap = Bootstrap()
db = SQLAlchemy()



def create_app(config_name):

    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(Config_options[config_name])

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
   
    

    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    # setting config
    from .request import configure_request
    configure_request(app)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/authenticate')

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,forms

app/main/views.py
from flask import abort, redirect, render_template, request, url_for,abort,flash
from flask_login import current_user, login_required, login_user, logout_user, login_manager

from app.request import get_quote

from .. import db
from ..user import Blog, Comment, User
from . import main
from .forms import BlogForm, CommentForm, UpdateProfile,UpForm




@main.route('/', methods=['GET', 'POST'])
def index():
    '''
    View root page function that returns the index page and its data
    '''
    title = 'my blogquote'
    quote = get_quote()
    blogs = Blog.query.all()
    return render_template('index.html', title=title, quote=quote, blogs=blogs)


@main.route('/blog/new', methods=['GET', 'POST'])
@login_required
def blogs():
    """
    view blog function to create a new blog
    """
    blog_form = BlogForm()

    if blog_form.validate_on_submit():
        title = blog_form.title.data
        content = blog_form.content.data
        print(current_user._get_current_object().id)
        blog = Blog(user_id=current_user._get_current_object().id,
                    title=title, content=content)

        db.session.add(blog)
        db.session.commit()

        return redirect(url_for('main.index'))

    return render_template('new_blog.html',  blog_form=blog_form)

@main.route("/post/<int:post_id>")
@login_required
def mypost(post_id):
    comments = Comment.query.filter_by(post_id=post_id).all()
    print(comments)
    heading = 'comments'
    blog = blog.query.get_or_404(post_id)
    return render_template('posts.html', title=blog.title, blog=blog, comments=comments, heading=heading)

@main.route('/delete/blog,<int:id>', methods=['GET', 'POST'])
@login_required
def delete_blog(id):
    blog = Blog.query.filter_by(id=id).first()
    if blog is not None:
        blog.delete_blog()
  
    return redirect(url_for('main.index',))

@main.route("/blog/update/<int:id>", methods=['GET', 'POST'])
@login_required
def update_blog(id):
    blog = Blog.query.filter_by(id = id).first()
    if blog is None:
        abort(404)
    form = UpForm()
    if form.validate_on_submit():
        title = form.title.data
        content = form.content.data
        print(current_user._get_current_object().id)
        blog = Blog(user_id=current_user._get_current_object().id,
                title=title, content=content)
        
        db.session.add(blog)
        db.session.commit()
    
        return redirect(url_for('main.index', blog_id=blog.id))
    elif request.method == 'GET':
        title = form.title.data
        content = form.content.data
    return render_template('blog.html',form=form)


@main.route('/user/<uname>')
@login_required
def profile(uname):
    user = User.query.filter_by(username=uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user=user)


@main.route('/user/<uname>/update', methods=['GET', 'POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username=uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile', uname=user.username))

    return render_template('profile/update.html', form=form)


@main.route('/comment/new/<int:blog_id>', methods=['GET', 'POST'])
@login_required
def new_comment(blog_id):
    form = CommentForm()
    blog = Blog.query.get(blog_id)
    if form.validate_on_submit():
        content = form.content.data

        new_comment = Comment(
            content=content, user_id=current_user._get_current_object().id, blog_id=blog_id)
        db.session.add(new_comment)
        db.session.commit()

        return redirect(url_for('.new_comment', blog_id=blog_id))

    comments = Comment.query.filter_by(blog_id=blog_id).all()
    print(comments)
    return render_template('comments.html', form=form, blog=blog, comments=comments)


@main.route('/delete/new/<int:id>', methods=['GET', 'POST'])
@login_required
def delete_comment(id):
    comment = Comment.query.filter_by(id=id).first()
    form = CommentForm()
    if comment is not None:
        comment.delete_comment()
        return redirect(url_for('main.index'))

    return render_template('comments.html', form=form)

app/templates/base.html
{% extends 'bootstrap/base.html'%}

        {% if title %}
        <title> {{ title }}</title>
        {% else %}
        <title> BLOGS </title>
        {% endif %}

        {% block styles%}
        {{ super() }}
        <link rel="stylesheet"type= "text/css" href="{{url_for('static',filename='css/styles.css')}}">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=Kaushan+Script&display=swap" rel="stylesheet">
      <style>
            body{
                background-image: url('https://img4.goodfon.com/wallpaper/nbig/8/b4/noutbuk-telefon-naushniki-kofe-tsvetok-tekhnika.jpg');
                background-repeat: no-repeat;
                background-size: cover;
            }
          
            li a {
  color: white;
  text-decoration: none;
}

.nav{
    display:flex;
    float:left;
}

.nav li{
    font-size: 20px;
    font-weight: bold;
}

.nav-user{
    float:right;
    text-decoration: none;
}

.nav-user li{
    text-decoration: none;
}
li a:hover{
    color:black;
}
/* Change the link color to #111 (black) on hover */

h1{
    color:green;
    font-weight: bolder;
    text-align: center;
    padding:30px;
    font-family: 'Kaushan Script', cursive;
    text-shadow: 5px 3px white;
    border-top: 2px solid white;
    border-bottom: 2px solid white;
    font-size: 70px;
}


.well-lg{
    display:inline-flex;
    padding-left:270px;
    padding-top: 50px;
    
}

.btn{
    background-color: green;
}
.card{
    text-align: center;
    padding:20px;
}
 #kadi{
    width:50rem;
} 

.navbar-collapse{
    background-color:#0c0b0b59;
}

.overlay{
    margin-top:0;
    padding:150px;
    background-color:#0c0c0cb8;
}

.sign{
    font-size: 30px;
    font-weight: bolder;
    text-decoration: none;
}

.nav-user{
    font-weight: bolder;
    font-size: 15px;
    text-decoration: none;
}
.nav-user li a{
    text-decoration: none;
}

.graph{
    color:white;
    padding:10px;
    font-weight: bolder;
}

.overlay-2{
    width:1000px;
    margin-left:80px;
    height:500px;
    background-color:#0c0c0cb8;
    padding-left: 50px;
    padding-top:100px;  
}
.overlay-1{
    width:1000px;
    margin-left:80px;
    height:500px;
    background-color:#0c0c0cb8;
    padding-left: 50px;

}
label{
    color :white;
}

input{
    padding:50px;
}
.container-2{
    padding-top:10px;
}
.container-1{
    padding-top:90px;
}
.nav-user li a:hover{
    color:black;
    text-decoration: none;
}
    </style>
        {% endblock %}
        <!-- Content block -->

        {% block content %}
        <!-- Navbar block  --> 
        {% block navbar %}
            {% include 'navbar.html' %}
        {% endblock %}

        {% endblock%}
<

app/templates/index.html
{% extends 'base.html' %}

    {% block content %}
    <div class="overlay">
    <h1>QUOTES BLOG </h1>

    <div class="well-lg" id="random">
        <div class="card" id="kadi">
            <div class="card-body">
                <h5 class="card-title">Author: {{quote.author}}</h5>
                <p class="card-text">{{quote.quote}}</p>
                <a href="{{quote.permalink}}" class="btn btn-success">MORE DETAILS</a>
            </div>
        </div>
    </div>
</div>

    {% endblock %}

app/templates/navbar.html
{% block content %}
    
      <div class="navbar-collapse">
        <ul class="nav ">
          <li><a href="/">Home</a></li>
          <li><a href="{{url_for('main.blogs',uname=current_user.username)}}">add a quote</a></li>
          <li><a href="/"> quotes </a></li>
        </ul>
  
        <ul class="nav-user">
          {% if current_user.is_authenticated %}
  
          <li style="color:white;padding:15px;">{{current_user.username}}</li>
          <li><a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
          <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
          {% else %}
          <li><a class="sign" href="{{url_for('auth.login')}}">Sign in</a></li>
          {%endif%}
        </ul>
      
    </div>
  </div>

  {% endblock %}

app/templates/new_blog.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf%}
<!DOCTYPE html>
<html>

<head>
  <meta charset='utf-8'>
  <meta http-equiv='X-UA-Compatible' content='IE=edge'>

<body>

  {% block content %}
  <div class="container">
    <div class="row">
      <div class="col-md-2"> </div>
      <div class="col-md-8">

        {{wtf.quick_form(blog_form)}}
        <div>

        </div>
      </div>
    </div>


    {% endblock%}


</body>

</html>

app/templates/post.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf%}
{% from 'display_comment_macro.html' import display_comments as commentDisplay%}
{% block content %}
<article class="media content-section">
    <img class="rounded-circle article-img"
         src="{{ url_for('static', filename='profile_pic/' + post.author.image_file) }}">
    <div class="media-body">
        <div class="article-metadata-1">
            <a class="mr-2" id="autha" href="#">{{ post.author.username }}...</a>
            <small class="text-muted saa">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            <div>
                <button class="btn btn-info btn-sm m-1" id="com" data-target="#commentModal" data-toggle="modal" type="button">
                    Comment
                </button>
                {% if post.author == current_user %}
                <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('main.update_post', post_id=post.id) }}">Update</a>
                <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">
                    Delete
                </button>
                {% endif %}
            </div>
        </div>
        <h2 class="article-title">{{ post.title }}</h2>
        <p class="article-content-1">{{ post.content }}</p>
    </div>
</article>

<article class="media content-section">
    <div class="media-body">
        <div class="article-metadata">
            <h1>{{commentDisplay(comments)}}</h1>
        </div>
    </div>
</article>
<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <form action="{{ url_for('main.delete_post', post_id=post.id) }}" method="POST">
                    <input class="btn btn-danger" type="submit" value="Delete">
                </form>
            </div>
        </div>
    </div>
</div>
<!-- Modal -->
<div class="modal fade" id="commentModal" tabindex="-1" role="dialog" aria-labelledby="commentModalTitle"
     aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="commentModalTitle">Comment</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="POST" action="{{url_for('main.comment',post_id = post.id)}}">
                    <div class="form-group">
                        <label for="title" id="oket" class="col-form-label">Title:</label>
                        <input type="text" class="form-control" id="title">
                    </div>
                    <div class="form-group">
                        <label for="comment" id="paul" class="col-form-label">Comment:</label>
                        <textarea class="form-control" id="comment" name="newcomment"></textarea>
                    </div>


                    <div class="modal-footer">
                        <button type="button" id="lor" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" id="lor" class="btn btn-primary">Add Comment</button>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
  <div class="row">
    <!-- displaying  Username-->
    <div class="col-md-6">
      <h3> {{user.username| capitalize}} </h3>

      <!--Displaying user bio-->
      {% if user.bio %}
      <p> {{user.bio}}</p>
      {%else%}
      <p> {{user.username| capitalize}} update your bio</p>
      {% endif %}

     

      {% if user == current_user %}
      <a href="{{url_for('main.update_profile',uname=current_user.username)}}">update bio</a>

      {% endif %}



    </div>


  </div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}